"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, KeyRound, LockKeyhole, Mail } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { cloudHydrate } from "@/lib/storage";

export function AuthForm() {
  const client = getSupabaseBrowserClient();
  const [mode,setMode]=useState<"signin"|"signup"|"reset">("signin");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [userEmail,setUserEmail]=useState("");
  useEffect(()=>{ if (!client) return; void client.auth.getUser().then(({data})=>setUserEmail(data.user?.email??"")); const {data}=client.auth.onAuthStateChange((_event,session)=>setUserEmail(session?.user.email??"")); return ()=>data.subscription.unsubscribe(); },[client]);
  async function submit(event:FormEvent){ event.preventDefault(); setBusy(true); setError(""); setMessage(""); if(!client){setError("Cloud accounts are not configured in this deployment. Guest study remains fully available in this browser.");setBusy(false);return;} try { if(mode==="reset"){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth`});if(error)throw error;setMessage("Check your email for a secure password reset link.");} else if(mode==="signup"){const {error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback`}});if(error)throw error;setMessage("Account created. Check your email if confirmation is required.");} else {const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;await cloudHydrate();setMessage("Signed in. Your cloud library and history have been restored.");} } catch(err){setError(err instanceof Error?err.message:"Authentication failed.");} finally{setBusy(false);} }
  if(userEmail) return <div className="panel"><div className="panel-body" style={{textAlign:"center",padding:50}}><span className="empty-icon"><Check/></span><h2>You’re signed in.</h2><p className="muted">{userEmail}</p><p>Your study guides and completed attempts sync through row-level-secured tables.</p><div style={{display:"flex",justifyContent:"center",gap:10,flexWrap:"wrap"}}><button className="button secondary" onClick={async()=>{await client?.auth.signOut();setUserEmail("");}}>Sign out</button><button className="button danger" onClick={async()=>{if(!window.confirm("Delete your StudyForge account and all cloud data? This cannot be undone."))return;const {error}=await client?.rpc("delete_my_studyforge_data")??{};if(error){setError(error.message);return;}await client?.auth.signOut();localStorage.clear();setUserEmail("");setMessage("Account and cloud data deleted.");}}>Delete account</button></div></div></div>;
  return <div className="panel"><div className="panel-head"><div><h3>{mode==="signup"?"Create your account":mode==="reset"?"Reset your password":"Welcome back"}</h3><p className="muted small" style={{margin:"4px 0 0"}}>The main quiz experience never requires an account.</p></div><LockKeyhole color="var(--accent)"/></div><form className="panel-body" onSubmit={submit}>{!client&&<div className="warning" style={{marginBottom:16}}>Cloud auth is not configured. Add the Supabase variables from <code>.env.example</code> to enable it.</div>}{error&&<div className="error" role="alert" style={{marginBottom:16}}>{error}</div>}{message&&<div className="success" role="status" style={{marginBottom:16}}>{message}</div>}<div className="field"><label htmlFor="email">Email address</label><div style={{position:"relative"}}><Mail size={17} style={{position:"absolute",left:12,top:13,color:"var(--muted)"}}/><input className="input" style={{paddingLeft:38}} id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div></div>{mode!=="reset"&&<div className="field"><label htmlFor="password">Password</label><div style={{position:"relative"}}><KeyRound size={17} style={{position:"absolute",left:12,top:13,color:"var(--muted)"}}/><input className="input" style={{paddingLeft:38}} id="password" type="password" autoComplete={mode==="signup"?"new-password":"current-password"} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></div></div>}<button className="button primary full" disabled={busy}>{busy?<><span className="loader"/> Please wait…</>:mode==="signup"?"Create account":mode==="reset"?"Send reset link":"Sign in"}</button>{client&&mode!=="reset"&&<button type="button" className="button secondary full" style={{marginTop:10}} onClick={async()=>{await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback`}});}}>Continue with Google</button>}<div style={{display:"flex",justifyContent:"space-between",marginTop:18}}><button type="button" className="button ghost" onClick={()=>setMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"Already have an account?":"Create an account"}</button><button type="button" className="button ghost" onClick={()=>setMode(mode==="reset"?"signin":"reset")}>{mode==="reset"?"Back to sign in":"Forgot password?"}</button></div></form></div>;
}
